project:
  type: book
  output-dir: ../docs

book:
  title: "docs"
  author: "Stefano Rapisarda"
  date: "2/5/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo



